name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Run npm i
          run: ./.github/scripts/index.sh
        - name: "Build Changelog"
          id: build_changelog
          uses: mikepenz/release-changelog-builder-action@{latest-release}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: tag name
          run: ./.github/scripts/tracker.sh
        

    
