# This is a basic workflow to help you get started with Actions

name: prod

# Controls when the workflow will run
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: ./index.sh

    
