name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
      runs-on: ubuntu-latest
      env:
          OAuth: ${{ secrets.OAUTH_ID }}
          OrganizationId: ${{ secrets.ORGANIZATION_ID}}
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Create task in tracker
          id: taskId
          run: ./.github/scripts/tracker.sh          
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Build app
          run: ./.github/scripts/index.sh
        - name: Run tests
          run: ./.github/scripts/test.sh
        - uses: docker-practice/actions-setup-docker@master
        - name: Build docker image
          run: ./.github/scripts/docker.sh
        
        

    
