name: prod
on:
  create:
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run npm i
        run: ./.github/scripts/index.sh
        

    
